### ISSUE TITLE
Pool information is outdated

### ISSUE THREAD

**Issue by Jasper-Nelligan** [thanpolas/uniswap-chain-queries#4]
Hi,

I tried running `getPriceUniswapV2()` in my script using an Infura node but it seems to be returning outdated LP information. For example, this is the data I get back (using your example in the README for `getPriceUniswapV2()`)

```
{
  price: '2927.60528',
  priceFormatted: '2,927.60528',
  priceRev: '0.00034158',
  priceRevFormatted: '0.00034158',
  token0Reserves: '15232136.02016',
  token1Reserves: '5202.93365',
  token0ReservesFormatted: '15,232,136.02',
  token1ReservesFormatted: '5,202.93',
  lpAddress: '0xa478c2975ab1ea89e8196811f51a7b7ade33eb11'
}
```

However when I go to the same pool at https://v2.info.uniswap.org/pair/0xa478c2975ab1ea89e8196811f51a7b7ade33eb11 it says the total DAI is 10,500,000, not 15,200,00 as returned by the query.

Is there a way to grab LP data from the latest block?

By the way, thanks for creating this project, it's very easy to use :+1:

**Comment by thanpolas** [comment]
well, maybe infura RPC is lagging? Try different providers... 

ethers.js, uses the "latest block" tag by default ... so, it's all about which provider you use and if and to what extend it lags behind...

**Comment by Jasper-Nelligan** [comment]
Thanks for the response @thanpolas. It turns out I was using the default ethers.provider instead of the Infura provider I had set up.

It works great now 👍
